if(UNIX AND NOT APPLE)
    pkg_check_modules(SDL3 REQUIRED IMPORTED_TARGET sdl3)
    pkg_search_module(SDL3_TTF REQUIRED IMPORTED_TARGET SDL3_ttf sdl3-ttf)

    set(DASHBOARD_SDL_TARGET PkgConfig::SDL3)
    set(DASHBOARD_SDL_TTF_TARGET PkgConfig::SDL3_TTF)
    return()
endif()

set(CPM_DOWNLOAD_VERSION 0.40.8)
set(CPM_DOWNLOAD_LOCATION "${CMAKE_CURRENT_LIST_DIR}/CPM.cmake")

if(EXISTS "${CPM_DOWNLOAD_LOCATION}")
    file(SIZE "${CPM_DOWNLOAD_LOCATION}" CPM_DOWNLOAD_SIZE)
endif()

if(NOT EXISTS "${CPM_DOWNLOAD_LOCATION}" OR CPM_DOWNLOAD_SIZE EQUAL 0)
    file(DOWNLOAD
        "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake"
        "${CPM_DOWNLOAD_LOCATION}"
        EXPECTED_HASH SHA256=78ba32abdf798bc616bab7c73aac32a17bbd7b06ad9e26a6add69de8f3ae4791
        TLS_VERIFY ON
    )
endif()

include("${CPM_DOWNLOAD_LOCATION}")

set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
CPMAddPackage("gh:libsdl-org/SDL#release-3.4.8")

if(SDL_ADDED)
    list(PREPEND CMAKE_PREFIX_PATH "${SDL_BINARY_DIR}")
    set(SDL3_DIR "${SDL_BINARY_DIR}" CACHE PATH "Path to SDL3 package config" FORCE)
endif()

set(SDLTTF_VENDORED ON CACHE BOOL "" FORCE)
set(SDLTTF_SAMPLES OFF CACHE BOOL "" FORCE)
set(SDLTTF_INSTALL OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
CPMAddPackage("gh:libsdl-org/SDL_ttf#release-3.2.2")

set(DASHBOARD_SDL_TARGET SDL3::SDL3-static)
if(NOT TARGET ${DASHBOARD_SDL_TARGET})
    set(DASHBOARD_SDL_TARGET SDL3::SDL3)
endif()

set(DASHBOARD_SDL_TTF_TARGET SDL3_ttf::SDL3_ttf-static)
if(NOT TARGET ${DASHBOARD_SDL_TTF_TARGET})
    set(DASHBOARD_SDL_TTF_TARGET SDL3_ttf::SDL3_ttf)
endif()
